name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_PRIVATE_KEY }}

      - name: Update application on EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i $SSH_PRIVATE_KEY ubuntu@34.229.195.125 'cd /var/www/html/Restaurante-Luna-verde && git pull origin main'
